services:
  backend: 
    build: backend
    volumes: 
      -  ./backend:/workspace/backend:cached
    ports:
      - "3000:3000" 
    container_name: back-container
    restart: always
    links:
      - database 
  database: 
    build: database 
    container_name: database-container
    restart: always